Repository kalviumcommunity/S81_Bhavaniprasad_Capstone_QueryNest, pull requests merged in 2025-05, with the labels that each got.

#1 readme complete
  Readme.md
Labels: Review effort 1/5

#2 get api
  Backend/controllers/userRoute.js
Labels: Review effort 1/5

#3 post api
  Backend/controllers/userRoute.js
Labels: Review effort 1/5

#4 Schema
  Backend/Models/userModel.js
Labels: Review effort 1/5

#7 changed inline css to tailwind css
  Frontend/client/src/pages/login.jsx
Labels: Review effort 2/5

#9 changed css in forgetpassword page
  Frontend/client/src/pages/forgotpassword.jsx
Labels: Review effort 2/5

#10 put api
  Backend/controllers/messageRoute.js
Labels: Review effort 1/5

#11 react components
  Frontend/client/src/components/GoogleButton.jsx
  Frontend/client/src/components/GoogleSuccess.jsx
Labels: Review effort 1/5

#12 bruno files added
  Backend/QueryNest/delete questions.bru
  Backend/QueryNest/login.bru
  Backend/QueryNest/otp verfy.bru
  Backend/QueryNest/signup.bru
  Backend/QueryNest/upvote.bru
Labels: Review effort 1/5

#13 file uplode
  Backend/app.js
  Backend/controllers/messageRoute.js
  Frontend/client/src/pages/Home.jsx
Labels: Review effort 2/5

#14 authontication complete
  Backend/controllers/userRoute.js
  Frontend/client/src/pages/login.jsx
  Frontend/client/src/pages/signup.jsx
Labels: Review effort 2/5, Possible security concern

#15 google auth done
  Backend/config/passport.js
  Backend/controllers/userRoute.js
  Frontend/client/src/components/GoogleButton.jsx
Labels: Review effort 2/5, Possible security concern

#16 update and delete complete
  Backend/controllers/messageRoute.js
  Backend/controllers/userRoute.js
Labels: Review effort 1/5

#17 jwt used
  Backend/controllers/userRoute.js
  Frontend/client/src/pages/Home.jsx
Labels: Review effort 2/5
